 # This file should ensure the existence of records required to run the application in every environment (production,
 # development, test). The code here should be idempotent so that it can be executed at any point in every environment.
 # The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
 #
 # Example:
 #
 #   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
 #     MovieGenre.find_or_create_by!(name: genre_name)
 #   end
 Restaurant.create!([
      { name: '11 SPICES MULTI CUSINE RESTAURANT'.titlecase, city_id: 1 },
      { name: 'All day Parathas', city_id: 1 },
      { name: 'Amantran Bengali Restaurant', city_id: 1 },
      { name: 'Bakingo', city_id: 1 },
      { name: 'Balaji Govind Dosa', city_id: 1 },
      { name: 'Bhagyalaxmi Tiffin Centre', city_id: 1 },
      { name: 'Bhavani Tiffins & Snacks', city_id: 1 },
      { name: 'Bheemas Grand', city_id: 1 },
      { name: 'Biryaniwalla and Co', city_id: 1 },
      { name: 'Capital Multicuisine', city_id: 1 },
      { name: 'Curry Combos', city_id: 1 },
      { name: 'Food.com', city_id: 1 },
      { name: 'Ghrelin Cafe & Patisserie', city_id: 1 },
      { name: 'Harsha Deluxe Mess', city_id: 1 },
      { name: 'Hitech Bawarchi Food Court', city_id: 1 },
      { name: 'Homely', city_id: 1 },
      { name: 'Imperial Multi Cusine Restaurant', city_id: 1 },
      { name: 'Indira Darshini', city_id: 1 },
      { name: 'Istah', city_id: 1 },
      { name: 'Jaggi De Paranthe', city_id: 1 },
      { name: 'Krishe saphire roof top'.titlecase, city_id: 1 },
      { name: 'Krupa Mess & Tiffins', city_id: 1 },
      { name: 'Lucky Multicuisine Restaurant', city_id: 1 },
      { name: 'Lucky Restaurant', city_id: 1 },
      { name: 'LunchBox - Meals and Thalis', city_id: 1 },
      { name: 'Madhu restaurant'.titlecase, city_id: 1 },
      { name: 'Makhni Darbar', city_id: 1 },
      { name: 'Mehfil', city_id: 1 },
      { name: 'Millet Express', city_id: 1 },
      { name: 'MOHAMMEDIA MANDI HOUSE'.titlecase, city_id: 1 },
      { name: 'Mughal Restaurant', city_id: 1 },
      { name: 'Niagara Hotel', city_id: 1 },
      { name: 'Parathas &  more', city_id: 1 },
      { name: 'Protein Chef', city_id: 1 },
      { name: 'Pujabi Affair', city_id: 1 },
      { name: 'Pizza Hut', city_id: 1 },
      { name: 'Punjabi Paratha House', city_id: 1 },
      { name: 'Rahul Tiffins', city_id: 1 },
      { name: 'Rambharose - Bhattad ki Idli', city_id: 1 },
      { name: 'Rayala Vari Ruchulu', city_id: 1 },
      { name: 'Rayalaseema Ruchulu', city_id: 1 },
      { name: 'Sahuri Kitchen', city_id: 1 },
      { name: 'Sarvi', city_id: 1 },
      { name: 'Shadab Go', city_id: 1 },
      { name: 'Shah Ghouse', city_id: 1 },
      { name: 'Shahi Dastarkhwan', city_id: 1 },
      { name: 'Shahi Rasoi Multicusine', city_id: 1 },
      { name: 'Shree Santhosh Family Dhaba', city_id: 1 },
      { name: 'Shri Santosh Family Dhaba', city_id: 1 },
      { name: 'Sri Santosh Family   Dhaba', city_id: 1 },
      { name: 'Subbayya Gari Hotel', city_id: 1 },
      { name: 'Shriji Rasoi', city_id: 1 },
      { name: 'Taiba', city_id: 1 },
      { name: 'The Biryani Life', city_id: 1 },
      { name: 'The Bowl  Company', city_id: 1 },
      { name: 'The Southern Palate', city_id: 1 },
      { name: 'Taste of Rajasthan', city_id: 1 },
      { name: 'Teluguism', city_id: 1 },
      { name: 'The Masala House', city_id: 1 },
      { name: 'Thali 99', city_id: 1 },
      { name: 'Tipsy Topsy', city_id: 1 },
      { name: 'Udupi dosa house'.titlecase, city_id: 1 },
      { name: 'Varalakshmi Tiffins', city_id: 1 },
      { name: 'Sri Andhra Pulav.com', city_id: 1 },
      { name: "Vsista's Sri Lakshmi", city_id: 1 },
      { name: 'Zaza Mughal Biryani', city_id: 1 }
    ])
