class InsertRestaurants < ActiveRecord::Migration[8.0]
  def change
    Restaurant.create!([
      { name: '11 SPICES MULTI CUSINE RESTAURANT'.titlecase },
      { name: 'All day Parathas' },
      { name: 'Amantran Bengali Restaurant' },
      { name: 'Bakingo' },
      { name: 'Balaji Govind Dosa' },
      { name: 'Bhagyalaxmi Tiffin Centre' },
      { name: 'Bhavani Tiffins & Snacks' },
      { name: 'Bheemas Grand' },
      { name: 'Biryaniwalla and Co' },
      { name: 'Capital Multicuisine' },
      { name: 'Curry Combos' },
      { name: 'Food.com' },
      { name: 'Ghrelin Cafe & Patisserie' },
      { name: 'Harsha Deluxe Mess' },
      { name: 'Hitech Bawarchi Food Court' },
      { name: 'Homely' },
      { name: 'Imperial Multi Cusine Restaurant' },
      { name: 'Indira Darshini' },
      { name: 'Istah' },
      { name: 'Jaggi De Paranthe' },
      { name: 'Krishe saphire roof top'.titlecase },
      { name: 'Krupa Mess & Tiffins' },
      { name: 'Lucky Multicuisine Restaurant' },
      { name: 'Lucky Restaurant' },
      { name: 'LunchBox - Meals and Thalis' },
      { name: 'Madhu restaurant'.titlecase },
      { name: 'Makhni Darbar' },
      { name: 'Mehfil' },
      { name: 'Millet Express' },
      { name: 'MOHAMMEDIA MANDI HOUSE'.titlecase },
      { name: 'Mughal Restaurant' },
      { name: 'Niagara Hotel' },
      { name: 'Parathas &  more' },
      { name: 'Protein Chef' },
      { name: 'Pujabi Affair' },
      { name: 'Pizza Hut' },
      { name: 'Punjabi Paratha House' },
      { name: 'Rahul Tiffins' },
      { name: 'Rambharose - Bhattad ki Idli' },
      { name: 'Rayala Vari Ruchulu' },
      { name: 'Rayalaseema Ruchulu' },
      { name: 'Sahuri Kitchen' },
      { name: 'Sarvi' },
      { name: 'Shadab Go' },
      { name: 'Shah Ghouse' },
      { name: 'Shahi Dastarkhwan' },
      { name: 'Shahi Rasoi Multicusine' },
      { name: 'Shree Santhosh Family Dhaba' },
      { name: 'Shri Santosh Family Dhaba' },
      { name: 'Sri Santosh Family   Dhaba' },
      { name: 'Subbayya Gari Hotel' },
      { name: 'Shriji Rasoi' },
      { name: 'Taiba' },
      { name: 'The Biryani Life' },
      { name: 'The Bowl  Company' },
      { name: 'The Southern Palate' },
      { name: 'Taste of Rajasthan' },
      { name: 'Teluguism' },
      { name: 'The Masala House' },
      { name: 'Thali 99' },
      { name: 'Tipsy Topsy' },
      { name: 'Udupi dosa house'.titlecase },
      { name: 'Varalakshmi Tiffins' },
      { name: 'Sri Andhra Pulav.com' },
      { name: "Vsista's Sri Lakshmi" },
      { name: 'Zaza Mughal Biryani	' }
    ])
  end
end
